- name: testing variable precedence
  hosts: mongodb
  vars:
    NAME: Avinash_play
  #vars_files:
  #  - variables.yaml
  vars_prompt:
    - name: NAME
      prompt: "Please enter your name"
      private: false
  tasks:
    - name: variable at task level
  #     vars:
  #      NAME: Avinash-task
      ansible.builtin.debug:
        msg: "{{ NAME }}"

